councils = {
"Girl Scouts of California's Central Coast":1,
"Girl Scouts of Central California South":1,
"Girl Scouts of Central Maryland, Inc":1,
"Girl Scouts of Citrus Council, Inc.":1,
"Girl Scouts of Eastern Iowa and Western Illinois, Inc.":1,
"Girl Scouts of Eastern Massachusetts":1,
"Girl Scouts of Eastern Pennsylvania":1,
"Girl Scouts Heart of Central California":1,
"Girl Scouts of Maine, Inc.":1,
"Girl Scouts Minnesota and Wisconsin Lakes and Pines":1,
"Girl Scouts - North Carolina Coastal Pines":1,
"Girl Scouts of Orange County":1,
"Girl Scouts Carolinas Peaks to Piedmont, Inc.":1,
"Girl Scouts of San Gorgonio Council":1,
"Girl Scouts of San Jacinto Council":1,
"Girl Scouts of Southern Nevada, Inc.":1,
"Girl Scouts of Virginia Skyline, Inc":1,
"Girl Scouts of Western New York":1,
"Girl Scouts of Wisconsin - Badgerland Council, Inc.":1,
"Girl Scouts of Wisconsin Southeast":1 }